server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # React SPA – alle Routen auf index.html umleiten
    location / {
        try_files $uri $uri/ /index.html;
    }
}
